language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release"
  - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"
addons:
  apt:
    packages:
      - lcov
matrix:
  include:
    - os: linux
      compiler: gcc
      env: CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug -DDFK_COVERAGE=ON" UPLOAD_COVERAGE=YES
    - os: linux
      compiler: gcc
      env: CMAKE_ARGS="-DDFK_NAMED_COROUTINES=OFF"
script:
  - ./scripts/bootstrap.sh
  - mkdir build
  - cd build
  - cmake $CMAKE_ARGS ..
  - VERBOSE=1 cmake --build . -- -j
  - cmake --build . --target test
  - cat Testing/Temporary/LastTest.log
after_success:
  - cd ..
  - if [[ "$UPLOAD_COVERAGE" == "YES" ]]; then ./scripts/coverage.sh; fi
notifications:
  email:
  - isn@extrn.org
