language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release"
  - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"
matrix:
  include:
    - os: linux
      compiler: gcc
      env: CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug -DDFK_ENABLE_COVERAGE=ON" COVERALLS=YES
before_install:
  - if [[ "$COVERALLS" == "YES" ]]; then pip install --user cpp-coveralls; fi
script:
  - ./scripts/bootstrap.sh
  - mkdir build
  - cd build
  - cmake $CMAKE_ARGS ..
  - VERBOSE=1 cmake --build . -- -j
  - cmake --build . --target test
after_success:
  - if [[ "$COVERALLS" == "YES" ]]; then coveralls --exclude thirdparty --exclude ut --gcov-options '\-lp'; fi
notifications:
  email:
  - isn@extrn.org
