language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - ./scripts/bootstrap.sh
  - mkdir build
  - cd build
  - cmake ..
  - make -j
  - make test
notifications:
  email:
  - isn@extrn.org
